version: "3.8"

services:
  mysql:
    image: mysql:8.0
    privileged: true
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "service_com"
    ports:
      - "3306:3306"
    volumes:
      - new-mysql-data:/var/lib/mysql

  nestjs:
    image: ${IMAGE_BACK}
    privileged: true
    container_name: my-nestjs-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: my-mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: "0000"
      DB_DATABASE: service_com

  reactjs:
    image: ${IMAGE_FRONT}
    privileged: true
    container_name: my-reactjs-container
    restart: always
    ports:
      - "80:3001"

volumes:
  new-mysql-data:
